version: '3.8'

services:
  postgres:
    container_name: wisdon-postgres
    image: postgres:12.5-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $POSTGRES_USER']
      timeout: 1s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./infra/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - wisdon-network
  postgres-test:
    container_name: wisdon-postgres-test
    image: postgres:12.5-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5533:5432"
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $POSTGRES_USER']
      timeout: 1s
      retries: 10
    volumes:
      - ./infra/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - wisdon-network
volumes:
  pgdata:
    driver: local
networks:
  wisdon-network:
    driver: bridge
